packages:
  - 'packages/*'

catalog:
  # axios
  axios: ^1.7.9

  # globals
  globals: ^15.14.0

  # husky
  husky: ^9.1.7

  # commitlint
  '@commitlint/cli': ^19.7.1
  '@commitlint/config-conventional': ^19.7.1

  # typescript
  typescript: ^5.7.3
  typescript-eslint: ^8.22.0

  # eslint
  eslint: ^9.17.0
  '@eslint/js': ^9.17.0
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.16
  eslint-plugin-simple-import-sort: ^12.1.1
  eslint-plugin-prettier: ^5.2.3
  eslint-plugin-storybook: ^0.11.2

  # prettier
  prettier: ^3.4.2
  eslint-config-prettier: ^10.0.1
  prettier-plugin-tailwindcss: ^0.6.11

  # react
  react: ^18.3.1
  react-dom: ^18.3.1
  '@types/react': ^18.3.18
  '@types/react-dom': ^18.3.5
  lucide-react: ^0.474.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1

  # tailwindcss
  tailwindcss: ^4.0.3
  '@tailwindcss/vite': ^4.0.3
  '@tailwindcss/postcss': ^4.0.3
  postcss: ^8.5.1
  tailwind-merge: ^3.0.1
  tailwindcss-animate: ^1.0.7

  # i18n
  i18next-browser-languagedetector: ^8.0.2
  react-i18next: ^15.4.0
  i18next: ^24.2.2
  i18next-resources-for-ts: ^1.5.0

  # jwt-decode
  jwt-decode: ^4.0.0

  # storybook
  storybook: ^8.5.3
  '@storybook/addon-essentials': ^8.5.3
  '@storybook/addon-interactions': ^8.5.3
  '@storybook/react': ^8.5.3
  '@storybook/react-vite': ^8.5.3
  '@storybook/test': ^8.5.3
  '@chromatic-com/storybook': ^3.2.4

  # vite
  vite: ^6.0.5
  vite-tsconfig-paths: ^5.1.4
  '@vitejs/plugin-react': ^4.3.4
  '@vitejs/plugin-react-swc': ^3.5.0

  # vitest
  vitest: ^3.0.4
  '@vitest/coverage-v8': ^3.0.4

  # testing-library
  '@testing-library/dom': ^10.4.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.2.0
  '@testing-library/user-event': ^14.6.1

  # jsdom
  jsdom: ^26.0.0
